### ISSUE TITLE
Page - Select Role

### ISSUE THREAD

**Issue by raysummee** [Megabyte-143/certified_cliche#22]
## Page - Select Role
tracking in #15 

### description:
The user need to select the role when the web app appear. After that the user will be redirect to particular flow.

### Figma page name:
* 1. select role

(both are the same page with different functionality)

### The folder should be like follows:
 js: components/components-name/components-name.js
 css: components/components-name/components-name.module.css

**Comment by Supriya2922** [comment]
I would like to work on this issue.

**Comment by raysummee** [comment]
@Supriya2922 I have assigned this issue to you. You can start working on it. All the best.

**Comment by Supriya2922** [comment]
Hey,
I actually have my sem exam tomorrow. So I was studying for that from
yesterday. (It's a very difficult subject :Automata theory) Due to which I
could not start with this issue:(
I'll start it  and try to finish it by tomorrow or Saturday. Is it okay?
This is my first time contributing and I really want to work on it.
Is it fine?
