### ISSUE TITLE
Function To Login Through Wallet using Moralis

### ISSUE THREAD

**Issue by Megabyte-143** [Megabyte-143/certified_cliche#48]
**Description** 
=> 
The 2nd Screen of [Figma](https://www.figma.com/file/HjYi7KbugT0xsXoA7arIN2/Certified-Cliche?node-id=0%3A1) which will login the user to the platform and will redirect him to the page (if it's organisation then Organisation dashboard [3rd Screen], if it's an applicant then Applicant Dashboard [9th Screen] ).

**[MORALIS](https://moralis.io/) SDK need to be use in this** 

**Task**
=> Make a function in `client` directory which will Login the user using **Wallet Connect**

*You may refer[ here](https://docs.moralis.io/moralis-server/users/crypto-login/walletconnect)*

**Comment by Supriya2922** [comment]
I would like to work on this issue.

**Comment by raysummee** [comment]
@Supriya2922 I'll assign you after your PR is merged. 

* Tracking at #61

**Comment by Supriya2922** [comment]
Okay

**Comment by Megabyte-143** [comment]
@Supriya2922 What's the status? It's already more than 2 days. Please let us know.

**Comment by Supriya2922** [comment]
I'm sorry :( I couldn't work on it because of my sem exams.I will start working on it from today . I have few doubts though about the workflow. On clicking on organization or individual this modal should appear?
![wallet](https://user-images.githubusercontent.com/72089269/157824019-1900f06a-12c8-4b80-af1b-39c6b4623ae0.png)
And on clicking on any of those metamask  icon , wallet connect should happen?
Can you please tell me why there are two metamask icons ?

**Comment by Supriya2922** [comment]
I completed the modal. Is this fine?
![walletSign](https://user-images.githubusercontent.com/72089269/157890313-03f4d8f5-b266-416d-852f-95db3408ced3.png)

**Comment by Megabyte-143** [comment]
Yes
